#!/bin/bash
source .venv/bin/activate
python -m jepax.train.train_ijepa \
    --seed 0 \
    --num_workers 8 \
    --xla_buckets 64 128 192 256 \
    --num_pad 64 \
    --data_name imnet \
    --data_dir ~/data/imagenet \
    --model_name ijepa-b \
    --tag 768b \
    --save_dir ~/checkpoints/ijepa/ijepa-b-imagenet \
    --save_interval 10 \
    --use_wandb \
    --wandb_project ijepa \
    --patch_size 14 \
    --seq_len 256 \
    --num_channels 3 \
    --batch_size 1024 \
    --epochs 300 \
    --eval_interval 1 \
    --eval_train_samples 100000 \
    --eval_val_samples 5000 \
    --eval_epochs 50 \
    --n_concat 4 \
    --weight_decay 0.04 \
    --final_weight_decay 0.4 \
    --start_lr 1e-4 \
    --lr 1e-3 \
    --end_lr 1e-6 \
    --warmup_epochs 40 \
    --ema_decay 0.996 \
    --num_pred_masks 4 \
    --pred_scale 0.15 0.2 \
    --pred_aspect 0.75 1.5 \
    --ctx_scale 0.85 1.0 \
    --ctx_aspect 1.0